;;; ghostherd-tmux.el --- tmux as a headless PTY host -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; tmux is here as a *named, detachable PTY that can dump its own
;; screen*, not as a second multiplexer.  Emacs already multiplexes;
;; putting tmux windows or panes in the middle would be a third
;; navigation layer inside ghostel.  So: one ghostherd session = one
;; tmux session on a dedicated socket, one window, one pane, status off,
;; prefix off.  The user's own tmux is untouched.
;;
;; Two things this buys, in order of size:
;;
;; 1. `capture-pane' reads the agent's screen directly.  Detection no
;;    longer scrapes a rendering of a rendering, works when nothing is
;;    attached, and does not care what ghostel has drawn yet.
;; 2. The agent outlives Emacs, and the recipe to describe it is stashed
;;    on the tmux session itself, so the herd can be restored.
;;
;; Attaching is optional and is the only thing that costs a nested VT:
;; visiting a session runs `tmux attach' inside a ghostel buffer.
;; Closing that buffer detaches; the agent keeps running.

;;; Code:

(require 'cl-lib)
(require 'subr-x)
(require 'ghostherd-backend)

(declare-function ghostel-exec "ghostel" (buffer program &optional args))

;; `defvar' without a value is a file-local declaration, so the shims in
;; ghostherd-backend.el do not carry over here.
(defvar ghostel--process)
(defvar ghostel--buffer-identity)
(defvar ghostel-kill-buffer-on-exit)

(defcustom ghostherd-tmux-executable "tmux"
  "Name or path of the tmux binary."
  :type 'string
  :group 'ghostherd)

(defcustom ghostherd-tmux-socket "ghostherd"
  "Socket name (tmux -L) ghostherd runs its own server on.

Dedicated on purpose: the user's default-socket tmux keeps its own
config, its own sessions and its own prefix key, and nothing here can
disturb it."
  :type 'string
  :group 'ghostherd)

(defconst ghostherd-tmux-config-text "\
# Generated by ghostherd -- edits are overwritten.  Point
# `ghostherd-tmux-config' at your own file to take this over.
#
# The point is to make tmux invisible: it is here as a named,
# detachable PTY that can dump its own screen, not as a second
# multiplexer.  An attached client should look like a raw terminal.

# No status bar and no prefix key: attaching happens inside a ghostel
# buffer, where a status line is a second, wrong mode-line and C-b
# would fight Emacs.  Detaching is `kill-buffer', an Emacs operation.
set -g status off
set -g prefix None
set -g prefix2 None
set -g mouse off

# An agent that exits stays capturable, so the sidebar can show `dead'
# with its last screen instead of the row vanishing underneath a poll.
# `ghostherd-kill' is what actually removes the session.
set -g remain-on-exit on
set -g destroy-unattached off

# Nobody is attached most of the time; do not let tmux reflow an
# agent's TUI to whatever client happens to glance at it.
set -g aggressive-resize off

# Escape is how you interrupt an agent.  The default half-second wait
# for a following key turns that into visible lag.
set -g escape-time 0

set -g history-limit 20000

# screen-256color is present everywhere; tmux-256color is not.  The
# override restores 24-bit colour, which agent CLIs lean on heavily.
set -g default-terminal \"screen-256color\"
set -ga terminal-overrides \",*:Tc\"
"
  "The tmux server config ghostherd writes and uses.

Generated rather than shipped as a file next to this one.  The obvious
version -- a .conf beside the source, found through `load-file-name' --
works from a checkout and quietly does not once the package is built:
package managers copy the files their recipe lists, and a lone .conf is
not on anybody's default list.  The failure is silent and remote from
its cause: no config means `remain-on-exit off', so an agent that exits
takes its session with it and the herd row vanishes mid-poll.")

(defcustom ghostherd-tmux-config nil
  "Config file for the tmux server ghostherd runs, or nil to generate one.

Passed as `-f' on every invocation, which sounds redundant and is not.
tmux reads it once, in whichever process actually starts the server --
and the only ghostherd command that can start one is `new-session'.
Passing it always therefore guarantees the config is in force *before*
the first pane exists, which matters because `status off' changes how
many rows the pane has, and a fast CLI has already drawn its TUI by the
time a `set-option' after the fact would land.

It also means there is no server to keep alive between herds: tmux
exits when its last session goes, and the next spawn brings it back
configured.  If a stale server is somehow running without it,
`tmux -L ghostherd kill-server' is the recovery -- reconfiguring a
running server from Elisp is not."
  :type '(choice (const :tag "Generated" nil) file)
  :group 'ghostherd)

(defvar ghostherd-tmux--generated-config nil
  "Path of the generated config, once it has been written this session.")

(defun ghostherd-tmux--config-file ()
  "Return the tmux config file to use, writing the generated one if needed.

Returns nil if it cannot be written -- a herd with default tmux options
is worse than one with ghostherd's, but far better than one that
refuses to start."
  (or ghostherd-tmux-config
      ghostherd-tmux--generated-config
      ;; Expanded: `locate-user-emacs-file' happily returns
      ;; "~/.emacs.d/...", Emacs expands a tilde in a file name and tmux
      ;; does not -- it would take the config as missing and start with
      ;; its defaults, silently.
      (let ((file (expand-file-name
                   (locate-user-emacs-file "ghostherd-tmux.conf"))))
        (when (ignore-errors
                (unless (and (file-readable-p file)
                             (equal ghostherd-tmux-config-text
                                    (with-temp-buffer
                                      (insert-file-contents file)
                                      (buffer-string))))
                  (with-temp-buffer
                    (insert ghostherd-tmux-config-text)
                    ;; Explicit UTF-8: `write-region' without one calls
                    ;; `select-safe-coding-system', which *prompts* -- an
                    ;; error in batch and a wedged daemon otherwise.  The
                    ;; same lesson bin/ghostherd learned the hard way.
                    (let ((coding-system-for-write 'utf-8))
                      (write-region (point-min) (point-max) file nil 'silent))))
                t)
          (setq ghostherd-tmux--generated-config file)))))

(defcustom ghostherd-tmux-default-size '(120 . 40)
  "Columns and rows for a detached agent pane.

A detached tmux session has no client to take its size from, and the
default 80x24 makes agent CLIs wrap their UI in ways their screen rules
were never written against.  An attached client resizes the pane to its
own window, so this is the size the agent renders at while nobody is
looking."
  :type '(cons integer integer)
  :group 'ghostherd)

(defcustom ghostherd-tmux-status-ttl 1.0
  "Seconds a `list-panes' snapshot is reused before tmux is asked again.

Liveness is consulted far more often than it changes -- every poll, and
every mode-line redisplay through `ghostherd--ensure-sessions'.  One
snapshot answers for the whole herd, so the cost is one subprocess per
tick rather than one per session per redisplay."
  :type 'number
  :group 'ghostherd)

(defconst ghostherd-tmux-key-names
  '(("esc"       . "Escape")
    ("escape"    . "Escape")
    ("ret"       . "Enter")
    ("return"    . "Enter")
    ("enter"     . "Enter")
    ("tab"       . "Tab")
    ("space"     . "Space")
    ("up"        . "Up")
    ("down"      . "Down")
    ("left"      . "Left")
    ("right"     . "Right")
    ("backspace" . "BSpace")
    ("C-c"       . "C-c")
    ("C-d"       . "C-d")
    ("C-z"       . "C-z"))
  "Map ghostherd's friendly key names onto tmux key names.

The same vocabulary `ghostherd-key-aliases' maps onto ghostel's
encoder, so a caller says \"esc\" and neither backend cares.  Anything
unlisted is passed to tmux unchanged, which keeps its full key
vocabulary reachable.")


;;; Running tmux

(defun ghostherd-tmux--socket-args ()
  "Return the leading tmux arguments: ghostherd's socket and config.

See `ghostherd-tmux-config' for why `-f' is on every call rather than
on a one-off `start-server'."
  (append (list "-L" ghostherd-tmux-socket)
          (when-let* ((config (ghostherd-tmux--config-file)))
            (list "-f" config))))

(defun ghostherd-tmux--call (args)
  "Run tmux with ARGS on ghostherd's socket.  Return (STATUS . OUTPUT).

`call-process', never a shell string: every value that reaches tmux
here is free text -- a prompt, a note, a path -- and a shell in the
middle would need quoting that has already been got wrong once (see
bin/ghostherd).  UTF-8 is pinned in both directions and neither is
decorative: a captured screen is full of box drawing, and an argument
can be a prompt in any language on its way to `set-buffer'.  A guessed
coding system either mangles those or stops to ask."
  (condition-case error
      (with-temp-buffer
        (let* ((coding-system-for-read 'utf-8)
               (coding-system-for-write 'utf-8)
               (status (apply #'call-process ghostherd-tmux-executable nil t nil
                              (append (ghostherd-tmux--socket-args) args))))
          (cons status (buffer-string))))
    ;; tmux not installed, or not on `exec-path'.  A missing multiplexer
    ;; is a dead host, not a crash: the ghostel backend stays usable.
    (file-missing (cons 127 (error-message-string error)))))

(defun ghostherd-tmux--try (&rest args)
  "Run tmux with ARGS, returning its output, or nil when it failed."
  (pcase-let ((`(,status . ,output) (ghostherd-tmux--call args)))
    (and (eq status 0) output)))

(defun ghostherd-tmux--run (&rest args)
  "Run tmux with ARGS, returning its output; signal when it failed.
Used for the paths where silence would be worse than an error: a spawn
that did not spawn, a keystroke that went nowhere."
  (pcase-let ((`(,status . ,output) (ghostherd-tmux--call args)))
    (unless (eq status 0)
      (user-error "tmux %s failed: %s"
                  (car args) (string-trim (or output "no output"))))
    output))

(defun ghostherd-tmux-available-p ()
  "Return non-nil when the tmux binary can be found."
  (and (executable-find ghostherd-tmux-executable) t))

(defun ghostherd-tmux--ensure-available ()
  "Signal unless tmux can be found.

Checked at spawn, not on every poll: `exec-path' does not change
between two ticks of a 1.5-second timer, and everywhere else a missing
binary is already handled as a host that is simply not there --
including restore, which has to be a no-op on a machine without tmux so
the ghostel backend stays usable."
  (unless (ghostherd-tmux-available-p)
    (user-error "tmux not found (ghostherd-tmux-executable = %s)"
                ghostherd-tmux-executable)))


;;; Naming

(defun ghostherd-tmux--sanitize (name)
  "Return NAME reduced to characters that are safe in a tmux target.

tmux parses a target as `session:window.pane', so a colon or a dot in a
session name is a bug rather than a style problem.  Everything outside
[A-Za-z0-9_-] becomes an underscore."
  (let ((clean (replace-regexp-in-string "[^A-Za-z0-9_-]" "_" (or name ""))))
    (if (string-empty-p clean) "agent" clean)))

(defun ghostherd-tmux-session-name (project name)
  "Return the tmux session name for herd session NAME under PROJECT.

Two agents called `reviewer' in two projects have to be distinct on one
socket, and a full path cannot go in a tmux name.  The first eight hex
of the expanded path's SHA-1 is short, stable across Emacs restarts --
which is what restore depends on -- and free of target punctuation."
  (format "gh-%s-%s"
          (substring (secure-hash
                      'sha1
                      ;; `file-name-as-directory' before hashing: the same
                      ;; project reaches us as "/src/app" from one caller
                      ;; and "/src/app/" from another, and two spellings
                      ;; of one root would hash to two different herds.
                      (if project
                          (file-name-as-directory (expand-file-name project))
                        ""))
                     0 8)
          (ghostherd-tmux--sanitize name)))

(defun ghostherd-tmux--target (id)
  "Return the exact tmux target for session ID.

The trailing colon is not decoration.  Without a `=' prefix tmux
prefix-matches, so `gh-abc-rev' silently operates on `gh-abc-reviewer';
and `=NAME' alone is only understood by the commands whose target is a
plain session -- `set-option', `capture-pane' and `send-keys' parse a
window or pane target, where a bare `=NAME' resolves against the
current session instead.  `=NAME:' is exact and is accepted by all of
them.  `display-message' is the one that made this worth writing down:
given `=NAME' it prints an empty format rather than failing."
  (when (string-match-p "[:.]" id)
    (error "Invalid tmux session id: %s" id))
  (concat "=" id ":"))

(defun ghostherd-tmux--has-session-p (id)
  "Return non-nil when tmux session ID exists right now (uncached)."
  (and (ghostherd-tmux--try "has-session" "-t" (ghostherd-tmux--target id)) t))

(defun ghostherd-tmux--unique-id (project name)
  "Return an unused tmux session name for NAME under PROJECT.

The herd guarantees its own names are unique, but the socket outlives
this Emacs: a leftover session from a previous run can be sitting on
the name we are about to take."
  (let ((base (ghostherd-tmux-session-name project name))
        (n 1)
        (id nil))
    (setq id base)
    (while (ghostherd-tmux--has-session-p id)
      (setq n (1+ n)
            id (format "%s-%d" base n)))
    id))


;;; The recipe, stashed on the tmux session

(defconst ghostherd-tmux--recipe-options
  '((:name    . "@ghostherd-name")
    (:kind    . "@ghostherd-kind")
    (:project . "@ghostherd-project")
    (:command . "@ghostherd-command")
    (:args    . "@ghostherd-args")
    (:notes   . "@ghostherd-notes"))
  "Recipe fields and the tmux user options that hold them.

On the session itself rather than in a sidecar file: a file can be
deleted while the process it describes is still running, and the
session name is not big enough to carry a note.")

(defun ghostherd-tmux--encode (field value)
  "Encode recipe FIELD's VALUE as a tmux option string."
  (pcase field
    (:kind (if value (symbol-name value) ""))
    ;; A list cannot be one option value, and the arguments are free text
    ;; that can contain spaces and quotes.  JSON is already a dependency.
    (:args (json-serialize (vconcat (or value []))))
    (_ (or value ""))))

(defun ghostherd-tmux--decode (field value)
  "Decode tmux option VALUE back into recipe FIELD's Lisp value."
  (pcase field
    (:kind (and value (not (string-empty-p value)) (intern value)))
    (:args (and value (not (string-empty-p value))
                (ignore-errors
                  (append (json-parse-string value :array-type 'list) nil))))
    (_ (and value (not (string-empty-p value)) value))))

(defun ghostherd-tmux--write-recipe (id plist)
  "Stash the recipe in PLIST on tmux session ID."
  (let ((target (ghostherd-tmux--target id)))
    (pcase-dolist (`(,field . ,option) ghostherd-tmux--recipe-options)
      (ghostherd-tmux--run "set-option" "-t" target option
                           (ghostherd-tmux--encode field (plist-get plist field))))))

(defun ghostherd-tmux--option (id option)
  "Return tmux user OPTION on session ID, or nil when unset.

Only the single newline tmux adds is removed: a note is free text and
may legitimately end in blank lines."
  (when-let* ((out (ghostherd-tmux--try
                    "show-options" "-qv" "-t" (ghostherd-tmux--target id)
                    option)))
    (let ((value (if (string-suffix-p "\n" out) (substring out 0 -1) out)))
      (unless (string-empty-p value) value))))

(defun ghostherd-tmux--read-recipe (id)
  "Return the recipe plist stashed on tmux session ID.

Six calls rather than one `list-sessions -F': two of these fields are
free text that may contain the very newlines and tabs a single
formatted line would be split on.  Restore runs once, for a handful of
sessions."
  (let (plist)
    (pcase-dolist (`(,field . ,option) ghostherd-tmux--recipe-options)
      (setq plist (plist-put plist field
                             (ghostherd-tmux--decode
                              field (ghostherd-tmux--option id option)))))
    plist))


;;; Host status, cached per tick

(defvar ghostherd-tmux--status-cache nil
  "Cons of (TIMESTAMP . ALIST), the last `list-panes' snapshot.
ALIST maps a tmux session name to (DEAD-P . TITLE).")

(defun ghostherd-tmux--forget ()
  "Drop the cached host snapshot, after something changed it."
  (setq ghostherd-tmux--status-cache nil))

(defun ghostherd-tmux--snapshot ()
  "Return the alist of tmux session name → (DEAD-P . TITLE), cached."
  (let ((now (float-time)))
    (when (or (null ghostherd-tmux--status-cache)
              (> (- now (car ghostherd-tmux--status-cache))
                 ghostherd-tmux-status-ttl))
      (setq ghostherd-tmux--status-cache
            (cons now (ghostherd-tmux--read-snapshot))))
    (cdr ghostherd-tmux--status-cache)))

(defun ghostherd-tmux--read-snapshot ()
  "Ask tmux for every pane's session name, dead flag and title.

One call for the whole herd.  The title is last on the line because it
is the only field that can contain the separator."
  (let ((out (ghostherd-tmux--try
              "list-panes" "-a" "-F" "#{session_name}\t#{pane_dead}\t#{pane_title}")))
    (when out
      (delq nil
            (mapcar (lambda (line)
                      (when (string-match "\\`\\([^\t]*\\)\t\\([^\t]*\\)\t?\\(.*\\)\\'"
                                          line)
                        (cons (match-string 1 line)
                              (cons (equal (match-string 2 line) "1")
                                    (match-string 3 line)))))
                    (split-string out "\n" t))))))

(defun ghostherd-tmux--status (session)
  "Return (DEAD-P . TITLE) for SESSION, or nil when its host is gone."
  (when-let* ((id (ghostherd-session-host-id session)))
    (cdr (assoc id (ghostherd-tmux--snapshot)))))


;;; Attaching a view

(defun ghostherd-tmux--on-view-killed ()
  "Clear the session's view when its attach buffer is killed.

Detaching is an Emacs operation: `prefix None' means there is no
`C-b d', so killing the buffer is how you stop looking at an agent.  It
must not touch `state' -- the agent is still running."
  (when-let* ((session (ghostherd-get (current-buffer))))
    (when (eq (ghostherd-session-backend session) 'tmux)
      (setf (ghostherd-session-buffer session) nil))))

(defun ghostherd-tmux--attach (session)
  "Open a ghostel buffer attached to SESSION's tmux session."
  (ghostherd--require-ghostel)
  (let* ((id (ghostherd-session-host-id session))
         (bufname (ghostherd--buffer-name (ghostherd-session-name session)))
         (existing (ghostherd-session-buffer session))
         (buffer (if (buffer-live-p existing)
                     existing
                   (get-buffer-create bufname))))
    (unless (ghostherd-tmux--has-session-p id)
      (user-error "No tmux session %s" id))
    (with-current-buffer buffer
      (setq default-directory
            (or (ghostherd-session-project session) default-directory)))
    (ghostel-exec buffer ghostherd-tmux-executable
                  (append (ghostherd-tmux--socket-args)
                          (list "attach-session" "-t"
                                (ghostherd-tmux--target id))))
    (with-current-buffer buffer
      (rename-buffer bufname t)
      (setq-local ghostherd-session-id (ghostherd-session-id session))
      (setq-local ghostel--buffer-identity bufname)
      ;; The client dying means detached.  There is nothing worth keeping
      ;; on screen, and a stale view would be mistaken for a live one --
      ;; unlike the ghostel backend, where the dead buffer *is* the
      ;; evidence.
      (setq-local ghostel-kill-buffer-on-exit t)
      ;; The buffer is a client showing one screen; this is what makes it
      ;; scroll like the buffer it looks like.
      (when (fboundp 'ghostherd-terminal-mode)
        (ghostherd-terminal-mode 1))
      (add-hook 'kill-buffer-hook #'ghostherd-tmux--on-view-killed nil t))
    (setf (ghostherd-session-buffer session) buffer)
    buffer))


;;; The tmux implementor

(cl-defmethod ghostherd-backend-view-is-host-p ((_backend (eql tmux)))
  nil)

(cl-defmethod ghostherd-backend-capture
  ((_backend (eql tmux)) session &optional n)
  ;; No -e: the rules match text, not SGR.  No -J: these are TUI agents,
  ;; and joining wrapped lines invents text that was never on a row.  No
  ;; scrollback: an alt-screen TUI does not keep its UI in history, so
  ;; scraping history is how you match a permission prompt that scrolled
  ;; away and is no longer real.  The visible pane is what the rules
  ;; always wanted.
  (ghostherd--string-tail
   (or (ghostherd-tmux--try
        "capture-pane" "-p" "-t"
        (ghostherd-tmux--target (ghostherd-session-host-id session)))
       "")
   n))

(cl-defmethod ghostherd-backend-scrollback
  ((_backend (eql tmux)) session lines)
  ;; -S -N reaches back into the pane's history, which is the one thing
  ;; `capture-pane' is deliberately not allowed to do on the detect path.
  ;; -J is still off: joining wrapped lines invents rows nobody drew.
  (ghostherd-tmux--try
   "capture-pane" "-p" "-S" (format "-%d" lines) "-t"
   (ghostherd-tmux--target (ghostherd-session-host-id session))))

(cl-defmethod ghostherd-backend-scroll ((_backend (eql tmux)) session lines)
  ;; tmux copy mode is the only thing that can move a pane's view, but it
  ;; is driven here by command rather than by a prefix key, so it never
  ;; becomes a navigation layer the user has to learn.  `-e' is what makes
  ;; it invisible: scrolling back to the bottom leaves copy mode on its
  ;; own, so there is no mode to notice or get stuck in.
  ;;
  ;; One invocation, because this runs per wheel click.
  (let ((target (ghostherd-tmux--target (ghostherd-session-host-id session))))
    (and (ghostherd-tmux--try
          "copy-mode" "-e" "-t" target
          ";" "send-keys" "-X" "-N" (number-to-string (abs lines))
          "-t" target (if (> lines 0) "scroll-up" "scroll-down"))
         t)))

(cl-defmethod ghostherd-backend-send-text
  ((_backend (eql tmux)) session text submit)
  (let ((target (ghostherd-tmux--target (ghostherd-session-host-id session))))
    ;; set-buffer + paste-buffer rather than `send-keys -l', so the agent
    ;; sees one bracketed paste instead of a burst of typing.  -r keeps
    ;; the newlines as newlines; the default turns each one into a
    ;; carriage return, which submits every line of a multi-line prompt.
    (ghostherd-tmux--run "set-buffer" "-b" "ghostherd-paste" "--" text)
    (ghostherd-tmux--run "paste-buffer" "-d" "-p" "-r"
                         "-b" "ghostherd-paste" "-t" target)
    (when submit
      (ghostherd-tmux--run "send-keys" "-t" target "Enter"))))

(cl-defmethod ghostherd-backend-send-keys
  ((_backend (eql tmux)) session keys)
  (when keys
    (apply #'ghostherd-tmux--run
           "send-keys" "-t"
           (ghostherd-tmux--target (ghostherd-session-host-id session))
           (mapcar (lambda (key)
                     (or (alist-get key ghostherd-tmux-key-names
                                    nil nil #'equal)
                         key))
                   keys))))

(cl-defmethod ghostherd-backend-live-p ((_backend (eql tmux)) session)
  (and (ghostherd-session-host-id session)
       (assoc (ghostherd-session-host-id session)
              (ghostherd-tmux--snapshot))
       t))

(cl-defmethod ghostherd-backend-exited-p ((_backend (eql tmux)) session)
  ;; `remain-on-exit on' keeps the pane after the agent exits, so a dead
  ;; pane is a session we can still read but no longer talk to.
  (and (car (ghostherd-tmux--status session)) "process exited"))

(defun ghostherd-tmux--meaningful-title (title)
  "Return TITLE unless it is tmux's default, which says nothing.

An unset `#{pane_title}' is the host name, so a herd where no agent has
emitted OSC 2 would otherwise show a column of identical hostnames --
the same noise `ghostherd--buffer-title' drops when a shell echoes the
buffer name back."
  (when (stringp title)
    (let ((title (string-trim title)))
      (unless (or (string-empty-p title)
                  (equal title (system-name))
                  (equal title (car (split-string (system-name) "\\."))))
        title))))

(cl-defmethod ghostherd-backend-title ((_backend (eql tmux)) session)
  ;; Prefer the attached view: ghostel's VT parser has seen every OSC 2
  ;; since the client connected, and its buffer-local is free to read.
  ;; tmux tracks the same sequence as #{pane_title} when nobody is.
  (or (ghostherd--buffer-title (ghostherd-session-buffer session))
      (ghostherd-tmux--meaningful-title
       (cdr (ghostherd-tmux--status session)))))

(cl-defmethod ghostherd-backend-view ((_backend (eql tmux)) session)
  (let ((buffer (ghostherd-session-buffer session)))
    (if (and (buffer-live-p buffer)
             (process-live-p (buffer-local-value 'ghostel--process buffer)))
        buffer
      (ghostherd-tmux--attach session))))

(cl-defmethod ghostherd-backend-kill ((_backend (eql tmux)) session)
  (when-let* ((id (ghostherd-session-host-id session)))
    (ghostherd-tmux--try "kill-session" "-t" (ghostherd-tmux--target id))
    (ghostherd-tmux--forget)))

(cl-defmethod ghostherd-backend-rename
  ((_backend (eql tmux)) session new-name)
  (let* ((old (ghostherd-session-host-id session))
         (new (ghostherd-tmux--unique-id
               (ghostherd-session-project session) new-name)))
    (ghostherd-tmux--run "rename-session" "-t" (ghostherd-tmux--target old) new)
    (setf (ghostherd-session-host-id session) new)
    (ghostherd-tmux--run "set-option" "-t" (ghostherd-tmux--target new)
                         "@ghostherd-name" new-name)
    (ghostherd-tmux--forget)
    (let ((buffer (ghostherd-session-buffer session)))
      (when (buffer-live-p buffer)
        (with-current-buffer buffer
          (rename-buffer (ghostherd--buffer-name new-name) t)
          (setq-local ghostherd-session-id new-name)
          (setq-local ghostel--buffer-identity (buffer-name)))))))

(cl-defmethod ghostherd-backend-spawn ((_backend (eql tmux)) plist)
  (ghostherd-tmux--ensure-available)
  (let* ((name (plist-get plist :name))
         (project (plist-get plist :project))
         (command (plist-get plist :command))
         (args (plist-get plist :args))
         (id (ghostherd-tmux--unique-id project name))
         (size ghostherd-tmux-default-size))
    ;; Direct exec, not the ghostel backend's shell-then-type-the-command:
    ;; tmux does not need a shell in the way, so `ghostherd-spawn-delay'
    ;; and its guesswork do not apply.  Multiple trailing arguments are
    ;; passed to execvp as-is, so nothing here is shell-quoted.
    (apply #'ghostherd-tmux--run
           (append (list "new-session" "-d" "-s" id
                         "-c" (expand-file-name
                               (or (plist-get plist :directory) "~/"))
                         "-x" (number-to-string (car size))
                         "-y" (number-to-string (cdr size)))
                   (when command (cons command args))))
    (ghostherd-tmux--write-recipe id plist)
    (ghostherd-tmux--forget)
    (list :host-id id :buffer nil :started (and command t))))

(cl-defmethod ghostherd-backend-list ((_backend (eql tmux)))
  "Return recipes for every `gh-' session on ghostherd's socket.

No server, or no tmux at all, is a no-op rather than an error: the
ghostel backend has to stay usable on a machine without tmux.  Note
that no read-only tmux command starts a server, so restore never brings
one up just to find nothing."
  (when (ghostherd-tmux-available-p)
    (when-let* ((out (ghostherd-tmux--try "list-sessions" "-F"
                                          "#{session_name}")))
      (delq nil
            (mapcar
             (lambda (id)
               (when (string-prefix-p "gh-" id)
                 (let ((recipe (ghostherd-tmux--read-recipe id)))
                   (append (list :host-id id
                                 ;; A session missing its options is one
                                 ;; we did not write; fall back to the id
                                 ;; rather than dropping it, since it is
                                 ;; still on our socket.
                                 :name (or (plist-get recipe :name) id))
                           recipe))))
             (split-string out "\n" t))))))

(provide 'ghostherd-tmux)
;;; ghostherd-tmux.el ends here
