#+TITLE: Early-init.el
#+PROPERTY: header-args:emacs-lisp :tangle ./early-init.el :mkdirp yes

* What is this

  Emacs can be configured using an early init file (early-init.el).
  It's expected to be located under the =user-emacs-directory= and it's loaded very early in the startup process.

  before the graphical elements such as tool bar, the package manager is initialized and before loading the site files

  =both doom emacs and spacemacs use this trick=
  https://github.com/hlissner/doom-emacs
  https://github.com/syl20bnr/spacemacs

* start crafting

  Put =-*- lexical-binding: t; -*-= in the beginning of the file. This way, we don't need to call =(setq lexical-binding t)=.
  tips for optimization https://github.com/nilcons/emacs-use-package-fast

  https://www.gnu.org/software/emacs/manual/html_node/eintr/debug_002don_002dentry.html
  another debug way

  #+begin_src emacs-lisp
    ;;; mycraft --- Summary  -*- lexical-binding: t; -*-
    ;;; Copyright (C) 2020 mycraft maintainers
    ;;; Author: Jing
    ;;; package --- mycraft
    ;;; Commentary:

    ;;; Code:

    ;; (toggle-debug-on-error) temporarily for debug usage

  #+end_src

* grow the garbage collection threshold when initialize
  this will make it high performance because of lower gc times.

  #+begin_src emacs-lisp
    (setq gc-cons-threshold 64000000)
    ;;(add-hook 'after-init-hook #'(lambda ()
    ;; restore after startup
    ;;                               (setq gc-cons-threshold 800000)))
  #+end_src

* prevent redisplay before setup the ui

  #+begin_src emacs-lisp
    (setq-default inhibit-redisplay t
                  inhibit-message t)
    (add-hook 'window-setup-hook
              (lambda ()
                (setq-default inhibit-redisplay nil
                              inhibit-message nil)
                (redisplay)))
  #+end_src

* disable package enable at startup and some misc settings

  #+begin_src emacs-lisp
    (setq package-enable-at-startup nil)
    (setq load-prefer-newer noninteractive)
  #+end_src

* set up config home directory and loading custom settings
  #+begin_src emacs-lisp
    (defvar home-dir (file-name-directory load-file-name))
    (setq user-emacs-directory (expand-file-name "emacs-home" home-dir))
    (unless (file-exists-p user-emacs-directory)
      (mkdir user-emacs-directory t))

    (when (boundp 'native-comp-eln-load-path)
      (setcar native-comp-eln-load-path (expand-file-name "eln-cache/" user-emacs-directory)))

    (defvar jemacs-config-file (expand-file-name "config.el" home-dir))
    (defvar jemacs-settings-file (expand-file-name "settings.el" home-dir))
    (when (file-exists-p jemacs-config-file)
      (load jemacs-config-file nil 'nomessage))
  #+end_src

* UI adjustment

  *minimize ui interface*

  We can adjust the ui by setting the =default-frame-alist=. The following settings are found in the source code.

  | function             | frame-alist                            |
  |----------------------+----------------------------------------|
  | (scroll-bar-mode -1) | '(vertical-scroll-bars)                |
  | (menu-bar-mode -1)   | '(menu-bar-lines . 0)                  |
  | (tool-bar-mode -1)   | '(tool-bar-lines . 0)                  |
  | (set-fringe-mode 5)  | '(left-fringe . 5) '(right-fringe . 5) |
  | toggle-fullscreen    | '(fullscreen . maximized)              |


  #+begin_src emacs-lisp
    (add-to-list 'default-frame-alist '(vertical-scroll-bars))
    (add-to-list 'default-frame-alist '(menu-bar-lines . 0))
    (add-to-list 'default-frame-alist '(tool-bar-lines . 0))
    (add-to-list 'default-frame-alist '(left-fringe . 5))
    (add-to-list 'default-frame-alist '(right-fringe . 5))
    (add-to-list 'default-frame-alist '(fullscreen . maximized))
    ;; (add-to-list 'default-frame-alist '(background-color . "#292b2e")) ;; this will be overwrite by doom-themes
    (add-to-list 'default-frame-alist '(font . "Source Code Pro-15"))
  #+end_src

* Font setup & config background color

  #+begin_src emacs-lisp
    (defvar default-font-size 140)
    (set-face-attribute 'fixed-pitch nil :font "Source Code Pro" :height default-font-size)
    (set-face-attribute 'variable-pitch nil :font "Source Code Pro" :height default-font-size :weight 'regular)
  #+end_src

* Reference
  https://www.masteringemacs.org/article/whats-new-in-emacs-27-1
