* Customize your emacs (spacemacs is abandoned)

  Let's start to customize your emacs(+spacemacs+). Note the directory =mycraft= is an experimental of crafting self-spacemacs and that's what
  I am focusing on.

  Note: some directories are still preserved because I am not completely transfer all the functions and workflows from the =spacemacs=.

* Install

  Clone this repo to the =~/.emacs.d/private=

  #+begin_src shell
    git clone https://github.com/sillygod/spacemacs-private.git ~/.emacs.d/private
  #+end_src

  Or you can clone to other directory and then create a soft link to the directory.
  Choose the way you like!

* Description

  A minimum configuration to mimic the spacemacs' ux.

* Personal configuration

  Currently, I preffer put configuration in the file =.spacemacs= instead of using my =config= layer.

* Reference

 Here are some tutorials. In addition, I put some notes on the =spacemacs_tips.org=

   - https://emacs.stackexchange.com/questions/31244/how-can-i-disable-evil-in-help-mode
   - https://gitlab.com/xuhdev/dired-quick-sort/-/merge_requests/3 (interesting)
   - https://github.com/xiongtx/eros (interesting plugins)
   - https://endlessparentheses.com/
   - http://blog.lujun9972.win/tags/emacs%E4%B9%8B%E6%80%92/
   - [[https://github.com/lujun9972/emacs-document/blob/master/elisp-common/Emacs%E4%B8%AD%E7%9A%84%E9%82%A3%E4%BA%9B%E5%8A%A8%E7%94%BB%E6%95%88%E6%9E%9C.org][a collection of emacs notes]]
